impl: 'https://github.com/blend-os/tracks/raw/main'

track: 'blendos-base'

packages:
  - 'fish'
  - 'micro'
  - 'avahi'
  - 'nss-mdns'
  - 'smbclient'
  - 'polkit'
  - 'fuse3'
  - 'gparted'
  - 'ghostscript'
  - 'flatpak'
  #- 'python-pipx'

aur-packages:
  - 'floorp-bin'

services:
  - 'avahi-daemon'
  - 'polkit'
  - 'NetworkManager'

commands:
  - 'touch /etc/samba/smb.conf'
  - |
    sed -i 's/\(\[!UNAVAIL=return]\) files/\1 mdns_minimal [NOTFOUND=return] files/' /etc/nsswitch.conf
  - 'rm /etc/shells'
  - 'cp /usr/etc/shells /etc/shells'
